spring:
  profiles:
    active: local

  jpa:
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false

springdoc:
  swagger-ui:
    path: /docs/swagger
    url: /docs/openapi3.yaml
    disable-swagger-default-url: true
    persist-authorization: true
    display-request-duration: true
    default-model-expand-depth: 10
