logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

spring:
  config:
    import:
      - optional:file:.env-local[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/eatda?useUnicode=true&characterEncoding=UTF-8
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: eatda-storage-local

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations:
      - classpath:db/migration
      - classpath:db/seed/local

jwt:
  access-token-expiration: 1h
  refresh-token-expiration: 1d
  secret-key: ${LOCAL_JWT_SECRET_KEY}

oauth:
  client-id: ${OAUTH_CLIENT_ID}
  redirect-path: /login/callback
  allowed-origins:
    - "http://localhost:3000"

kakao:
  api-key: ${KAKAO_API_KEY}
